name: scada_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pymssql=2.2.7
  - pandas=1.5.3
  - numpy=1.24.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - jupyter=1.0.0
  - pip=23.0.1
  - pip:
    - matplotlib-inline==0.1.6